### ISSUE TITLE
Chore: Publish test coverage report

### ISSUE THREAD

**Issue by brunomenezes** [cartesi/rollups-explorer-api#10]
## 📄 Context
We are generating the coverage report for our unit test cases. But we are not doing much with it. That would be good to publish to our coveralls account. 

## 📈 Subtasks

- [x] Get permissions between the GitHub repository and coveralls sorted.
- [x] Update the GitHub Action called deploy.yaml to also publish the test results.
- [x] Add the coveralls badge to the README. 😉 

## 🎯 Definition of Done

- [x] The coverage report is successfully published
- [x] Coveralls badge added to the README

**Comment by nevendyulgerov** [comment]
Hey @brunomenezes , I need access to the `rollups-explorer-api` repo in coveralls in order to add it there. I think I need to request access for the entire cartesi org so I can add repos from that space to coveralls.

I think this is the right place to do it:
![Screenshot 2023-09-28 at 15 07 46](https://github.com/cartesi/rollups-explorer-api/assets/6005179/7a6439f7-0a19-4aa9-85c9-f8dd2c74b838)

In case I'm wrong, please let me know if there's a different way to do it.

**Comment by tuler** [comment]
Please check if you can see the project at https://coveralls.io/github/cartesi/rollups-explorer-api

**Comment by nevendyulgerov** [comment]
Yes, I can see the project now, thanks @tuler !
