### ISSUE TITLE
Process ERC-721 information

### ISSUE THREAD

**Issue by brunomenezes** [cartesi/rollups-explorer-api#18]
## 📄 Context
Support to the [ERC721Portal](https://next.docs.cartesi.io/cartesi-rollups/api/json-rpc/portals/ERC721Portal/) will be added to the UI, and we can process events from ERC-721 Portal to save handy information to provide consistent support to the UI like we already do with ERC-20. 

## ✔️ Solution
Index metadata about the ERC-721 token passing through the portal. Even if the `name` and `symbol` are not implemented as per Spec, we want to know that such a contract address was already used.

### Option 1
**Add a new Domain:**
Domain Name: `NFT`
Cardinality: 10
Fields: [`id: ID!`, `name: String`, `symbol: String`]

~### Option 2~
~Update the existing `Token` domain, making the fields `name`, `symbol` and `decimals` optional. Also, Add a field `type` enumerable `ERC20`, `ERC721` for easy filtering and that specific fields will always be `null` e.g. ERC-721 spec as per time of writing has no `decimals` metadata.~

EIP-721: https://eips.ethereum.org/EIPS/eip-721

## 📈 Subtasks

- [ ] Add ERC721 ABI.
- [ ] Index ERC-721 info for inputs coming from ERC721Portal address.
- [ ] Add test case.

## 🎯 Definition of Done

- [ ] Successfully index the ERC-721 token information.
