### ISSUE TITLE
Indexing new providers contracts

### ISSUE THREAD

**Issue by brunomenezes** [cartesi/rollups-explorer-api#23]
## 📄 Context
An original [PR on Sunodo](https://github.com/sunodo/sunodo/pull/234) has an implementation for indexing new provider contracts. However, we have a lot of commonalities, and the API could index such contracts.

## ✔️ Solution
Add the implementation of said contracts for indexing (use original PR as a reference). Also, consider the entity diagram below for implementation.

<details>
<summary><h3>Entity diagram</h3></summary>

![image](https://github.com/sunodo/sunodo/assets/73850/e2389249-5445-422c-a90b-45e6348e6ce1)

</details>

New contracts (ABI) and events of interest:
* AuthorityFactory
  * _AuthorityCreated (topic)_
* ValidatorNodeProvider
  * _MachineLocation (topic)_
  * _FinancialRunway (topic)_
  * _Paused (topic)_
  * _Unpaused (topic)_
* Marketplace 
  * _ValidatorNodeProviderCreated (topic)_ 

New Entities:
* Authority
* ValidatorNodeProvider
* ValidatorNode
* ReaderNodeProvider ??
* ReaderNode ??

## 📈 Subtasks

- [ ] Add new contract ABIs.
- [ ] Add new Entities to graphQL schema.
- [ ] Generate new migrations.
- [ ] Add new handlers for topics of interest.
- [ ] Add test cases.

## 🎯 Definition of Done

- [ ] Can successfully index the `AuthorityFactory`, `Marketplace` and `ValidatorNodeProvider` contract events.

**Comment by brunomenezes** [comment]
@tuler, 
In the original PR, I saw the definition of the `ReaderNodeProvider` and `ReaderNode` entities. However, I could not see an ABI nor any reference to saving during the implementation in the `main.ts` when working with the block/log. Is that some initial idea forgotten to clean up, or is it missing?
