### ISSUE TITLE
Replace deprecated methods and functions

### ISSUE THREAD

**Issue by brunomenezes** [cartesi/rollups-explorer-api#32]
## 📄 Context
The subquid deprecated a few things, such as an archive helper function and methods/types related to the processor configuration. We need to replace these accordingly and add new types if necessary.

Refs: 
* https://docs.subsquid.io/sdk/reference/processors/evm-batch/general/#set-data-source
* https://docs.subsquid.io/glossary/#archive-registry

## 📈 Subtasks

- [x] Replace the usage of `archiveLookup()` with recommendations from Subsquid docs.  
- [x] Replace the usage of `setDataSource()` with recommendations from Subsquid docs. 
- [x] Update broken tests. 
- [x] Test indexing for Mainnet
- [x] Test Indexing for Sepolia

**Comment by brunomenezes** [comment]
Done on #42
