### ISSUE TITLE
Multichain Indexing

### ISSUE THREAD

**Issue by brunomenezes** [cartesi/rollups-explorer-api#41]
## 📄 Context
The idea is to change the initial strategy of deployments by network and to have all the events of interest from the supported chains in a single backend. That would simplify the operational side (i.e. Deployments)

PS: Check the recommendations in the squid [multichain documentation](https://docs.subsquid.io/sdk/resources/basics/multichain/) section. 

## ✔️ Solution
Besides adding the multichain capability to the indexer, it should also be configurable so that I may want a specific number of the supported networks to be indexed, e.g. only Ethereum Mainnet and Sepolia. That would avoid resource waste. 

## 📈 Subtasks

- [ ] Implement the configuration logic
- [ ] Implement the indexing logic
- [ ] Update documentation

## 🎯 Definition of Done

- [ ] As a user I can configure and index all the supported networks
- [ ] As a user I can configure and only index specific supported networks

**Comment by brunomenezes** [comment]
@tuler, anything missing here? I think that covers also for Sunodo when you desire to index from a single or a few networks.

**Comment by tuler** [comment]
It looks like the solution you posted by subsquid puts data in a single database but different schemas for each network. And then you would have to highly customize the graphql.

**Comment by brunomenezes** [comment]
> It looks like the solution you posted by subsquid puts data in a single database but different schemas for each network. And then you would have to highly customize the graphql.

Do you say that because of that mention here?

```js
processor.run(
  new TypeormDatabase({
    stateSchema: 'eth_processor'
  }),
  async (ctx) => { // ...
```
In the past, I built a squid to look at activities on arbitrum, optimism, and base. That `stateSchema` name is necessary for each network, but I did not create the folder structure for each. It was a single main/processor. It looked like this in my case.

```js
processor.run(
    new TypeormDatabase({
      supportHotBlocks: true,
      stateSchema: `processor-${chain.id}`,
    }),
    async (ctx) => {
```
This schema will hold tables regarding blockchain information like height/nonce/hash so the processor knows where it left off. But the tables for the models defined are located in the public schema. 

<img width="407" alt="image" src="https://github.com/user-attachments/assets/4e3de23c-6544-4c04-bf11-152f8e9c61be">

The graphQL for the clients that are single chain (CartesiScan case) will be impacted; it will need to add the chain to filter only the data of interest.
