### ISSUE TITLE
Chore: Add event handlers test cases

### ISSUE THREAD

**Issue by brunomenezes** [cartesi/rollups-explorer-api#9]
## 📄 Context
We added a few test cases to the codebase with [Vitest](https://vitest.dev/). As we move from the experimentation phase to a more stable one, it is a good time to start covering the code written with some practical unit tests. For the scope of this issue, the **event handlers** are the ones to be covered, i.e. [`ApplicationCreated.ts`, `InputAdded.ts`, `OwnershipTransferred.ts`, `EventHandler.ts`]

## ✔️ Solution
Add a practical test case for each handler and do the necessary refactoring when necessary.

Reference: The way to go is to check the vast Vitest documentation. For quick ref, you could check the [processor.test.ts](https://github.com/cartesi/rollups-explorer-api/blob/main/tests/processor.test.ts) since Vitest is a bit different in some points compared with `Jest`

## 📈 Subtasks

- [ ] Add test cases for the ApplicationCreated handler
- [ ] Add test cases for InputAdded handler
- [ ] Add test cases for OwnershipTransferred handler
- [ ] Add test cases for the EventHandler holder.

## 🎯 Definition of Done

- [ ] The test cases are standalone
- [ ] The test cases run in isolation
- [ ] The test cases have no external dependency i.e. Database
- [ ] The CI checks are passing.
